apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ${DOCKER_USERNAME}/petclinic-config-server:${CONFIG_SERVER_TAG}
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: ${NAMESPACE}
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP
