apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: ${DOCKER_USERNAME}/petclinic-vets-service:${VETS_SERVICE_TAG}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: vets-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
