apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: ${DOCKER_USERNAME}/petclinic-visits-service:${VISITS_SERVICE_TAG}
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: visits-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
